/**
 * The wiki reads a slim copy of Palworld's own game data, generated by
 * `scripts/build-wiki-data.mjs` into `web/public/wiki`. Nothing here talks to
 * the Rust API — a loaded save is not needed to browse the reference.
 */

export interface WikiPal {
  id: string;
  name: string;
  description?: string;
  icon: string;
  isPal: boolean;
  dexIndex: number | null;
  elements: string[];
  rarity: number;
  size: string | null;
  genus: string | null;
  boss: boolean;
  nocturnal: boolean;
  scaling: { hp: number; attack: number; defense: number };
  stamina: number;
  foodAmount: number;
  price: number;
  speeds: {
    walk: number;
    run: number;
    rideSprint: number;
    transport: number;
  };
  work: Record<string, number>;
  skills: { id: string; level: number }[];
  passives: string[];
}

export interface WikiItem {
  id: string;
  name: string;
  description?: string;
  icon: string;
  group: string | null;
  typeA: string | null;
  typeB: string | null;
  rank: number;
  rarity: number;
  maxStack: number;
  weight: number;
  price: number;
}

export interface WikiEffect {
  type: string;
  value: number;
  target?: string;
  value_ex?: number;
}

export interface WikiActiveSkill {
  id: string;
  name: string;
  description?: string;
  element: string | null;
  type: string | null;
  power: number;
  cooldown: number;
  minRange: number;
  maxRange: number;
  effects: WikiEffect[];
}

export interface WikiPassiveSkill {
  id: string;
  name: string;
  description?: string;
  rank: number;
  effects: WikiEffect[];
  attachesTo: string[];
}

export interface WikiElement {
  id: string;
  name: string;
  description?: string;
  color: string;
  icon: string;
}

export interface WikiWorkType {
  id: string;
  name: string;
  description?: string;
  icon: string;
  pals: { id: string; name: string; level: number }[];
}

export interface WikiTechnology {
  id: string;
  name: string;
  description?: string;
  icon: string;
  tier: number;
  cost: number;
  levelCap: number;
  boss: boolean;
  requires: string | null;
  unlocksItems: string[];
  unlocksBuildings: string[];
}

export interface WikiBuilding {
  id: string;
  name: string;
  description?: string;
  icon: string;
  typeA: string | null;
  typeB: string | null;
  rank: number;
  hp: number;
  defense: number;
  energy: string | null;
  materials: { id: string; count: number }[];
}

export interface WikiDataSets {
  pals: WikiPal[];
  items: WikiItem[];
  "active-skills": WikiActiveSkill[];
  "passive-skills": WikiPassiveSkill[];
  elements: WikiElement[];
  "work-suitability": WikiWorkType[];
  technologies: WikiTechnology[];
  buildings: WikiBuilding[];
}

export type WikiDataSet = keyof WikiDataSets;

/** Data files are static and immutable per build, so one fetch each is enough. */
const cache = new Map<WikiDataSet, Promise<unknown>>();

export function loadWikiData<K extends WikiDataSet>(
  set: K,
): Promise<WikiDataSets[K]> {
  const pending =
    cache.get(set) ??
    fetch(`/wiki/data/${set}.json`)
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            `The ${set} data file is missing. Run scripts/build-wiki-data.mjs to generate it.`,
          );
        }
        return response.json();
      })
      .catch((cause: unknown) => {
        // A failed fetch must not poison the cache for a later retry.
        cache.delete(set);
        throw cause;
      });

  cache.set(set, pending);

  return pending as Promise<WikiDataSets[K]>;
}

/** Icons are copied out of the game data dump by the same script. */
export function wikiIconUrl(icon: string | null | undefined) {
  return icon ? `/wiki/img/${icon}.webp` : undefined;
}

export const WIKI_CATEGORIES = [
  {
    href: "/wiki/pals",
    label: "Pals",
    blurb: "Elements, stat scaling, work suitability and the skills each Pal learns.",
  },
  {
    href: "/wiki/items",
    label: "Items",
    blurb: "Every item ID, with type, stack size, weight and value.",
  },
  {
    href: "/wiki/active-skills",
    label: "Active skills",
    blurb: "Combat skills: element, power, range, cooldown and status effects.",
  },
  {
    href: "/wiki/passive-skills",
    label: "Passive skills",
    blurb: "Passive traits, what they modify and what they can roll on.",
  },
  {
    href: "/wiki/elements",
    label: "Elements",
    blurb: "The nine element types and which Pals belong to each.",
  },
  {
    href: "/wiki/work-suitability",
    label: "Work suitability",
    blurb: "Base jobs, and every Pal that can do each one, ranked by level.",
  },
  {
    href: "/wiki/technologies",
    label: "Technologies",
    blurb: "Tech tree entries with unlock level, point cost and what they unlock.",
  },
  {
    href: "/wiki/buildings",
    label: "Buildings",
    blurb: "Build recipes, materials, durability and power requirements.",
  },
] as const;

export const WIKI_DOCS = [
  {
    href: "/wiki/usage",
    label: "Usage",
    blurb: "Load a world, edit it, and export a save the game accepts.",
  },
  {
    href: "/wiki/reference",
    label: "Reference",
    blurb: "Save container, world collections, editing limits and the HTTP API.",
  },
  {
    href: "/wiki/faq",
    label: "FAQ",
    blurb: "Short answers to the questions the editor raises most often.",
  },
] as const;
