import type { Metadata } from "next";
import Link from "next/link";
import { WIKI_CATEGORIES, WIKI_DOCS } from "@/lib/wiki";
import { WikiHeader } from "@/components/wiki-ui";
import { ArrowRightIcon } from "@/components/icons";

export const metadata: Metadata = {
  title: "Wiki",
  description:
    "Palworld game data — Pals, items, skills, elements, technologies and buildings — alongside documentation for the editor itself.",
};

function Cards({
  pages,
}: {
  pages: readonly { href: string; label: string; blurb: string }[];
}) {
  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {pages.map((page) => (
        <Link key={page.href} href={page.href} className="card card-hover p-4">
          <h3 className="flex items-center gap-1.5 font-medium">
            {page.label}
            <ArrowRightIcon className="size-3.5 text-accent" />
          </h3>
          <p className="mt-1 text-sm text-muted">{page.blurb}</p>
        </Link>
      ))}
    </div>
  );
}

export default function WikiHomePage() {
  return (
    <>
      <WikiHeader
        title="Wiki"
        lead={
          <>
            Palworld&apos;s own game data, browsable offline, plus the
            documentation for this editor. Nothing here needs a save loaded —
            the IDs listed are the ones the editor writes.
          </>
        }
      />

      <section className="space-y-3">
        <h2 className="text-sm font-medium text-subtle">Game data</h2>
        <Cards pages={WIKI_CATEGORIES} />
      </section>

      <section className="space-y-3">
        <h2 className="text-sm font-medium text-subtle">Docs</h2>
        <Cards pages={WIKI_DOCS} />
      </section>

      <p className="text-xs text-subtle">
        Game data is extracted from Palworld and regenerated by{" "}
        <code>scripts/build-wiki-data.mjs</code>; it reflects the game version
        the dump was taken from, not necessarily the one you are playing.
        Palworld is © Pocketpair — this project is not affiliated with them.
      </p>
    </>
  );
}
